# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumulativeRows <- function(M) {
    .Call('_toyepidemic_cumulativeRows', PACKAGE = 'toyepidemic', M)
}

decideEvents <- function(events, probs_random) {
    .Call('_toyepidemic_decideEvents', PACKAGE = 'toyepidemic', events, probs_random)
}

